apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kqz2kvr29-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kqz2kvr29-go 
  name: kqz2kvr29-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kqz2kvr29-go 
